/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SonarTest;

import java.util.ArrayList;

public class Library {
	
	public void addition(int a , int b) {
		System.out.println(a + b);
	}
	
	public static void main(String[] args)
		Library obj = new Library();
		obj.addition(2,2);
    
}

