/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SonarTest;

import java.util.ArrayList;

public class Library {
	
	public static int findMax(int arr[]){  

        int max=0;  

        for(int i=1;i<arr.length;i++){  

            if(max<arr[i])  

                max=arr[i];  

        }  

        return max;  

    } 
}

