/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SonarTest;

import java.util.ArrayList;

public class Library {
	public void m1() {
    	ArrayList<Integer> list = new ArrayList<Integer>();
    	list.add(1);
    	list.add(2);
    	Object obj = getData();
    	//System.out.println(obj.toString());
    			
    }    
     
    public Object getData() {
    	return null;
    }
	
	public void addition(int a , int b) {
		int res = a + b;
	}
    
	public static void main( String[] args )
    {
       // System.out.println( "Hello World!" );
        Library app = new Library();
        app.m1();
    }
    
}

