/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SonarTest;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        System.out.println("My Test");
    }
}
