/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SonarTest;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test  

    public void FindMax(){  

        assertEquals(4,Calculation.findMax(new int[]{1,3,4,2}));  

        assertEquals(-1,Calculation.findMax(new int[]{-12,-1,-3,-4,-2}));  

    }
}
